apiVersion: v1
kind: Service
metadata:
  name: my-prometheus
  namespace: default
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: my-prometheus
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
