apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-manager
spec:
  selector:
    matchLabels:
      app: metrics-manager
  replicas: 1 
  template:
    metadata:
      labels:
        app: metrics-manager
    spec:
      containers:
      - name: metrics-manager
        image: docker.io/samridhigupta/metrics_manager:latest
        ports:
        - containerPort: 8080
