apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-prometheus
spec:
  selector:
    matchLabels:
      app: my-prometheus
  replicas: 1 
  template:
    metadata:
      labels:
        app: my-prometheus
    spec:
      containers:
      - name: my-prometheus
        image: docker.io/samridhigupta/my-prometheus:latest
        ports:
        - containerPort: 9090
